### ISSUE TITLE
@href should be able to do releases

### ISSUE THREAD

**Issue by faassen** [morepath/more.chameleon#2]
We should work out how to let @href do releases on PyPI for this project. I can give you the owner role, what's your pypi id?

Are you familiar with how to use `bin/fullrelease` to do a release? (zest.releaser)

**Comment by href** [comment]
I am not, I'm a bumpversion kind of guy myself. I'm sure I can read up about it though. My PyPI handle is `href` as well.

In any case note that I'm not currently using more.chameleon myself. I had some custom requirements (namely injecting some variables into the render function) and the integration with Morepath is so light that I simply added it myself.

However, I can change that, to make sure I'm dogfooding.

**Comment by faassen** [comment]
Okay, I made you package owner.

I didn't know a tool called bumpversion existed. It should add dates to its changelog like zest.releaser does! Anyway, the buildout installs zest.releaser so it should be easy enough to use `bin/fullrelease`.

Yeah, it'd be nice if _someone_ dogfooded this stuff, as I'm not using server side templating at all right now. :)

**Comment by href** [comment]
Thanks, I can do the next release one of these these.

> I didn't know a tool called bumpversion existed. It should add dates to its changelog like zest.releaser does!

It does, see https://github.com/morepath/more.webassets/blob/master/.bumpversion.cfg
But any tool is fine really.

> Yeah, it'd be nice if someone dogfooded this stuff, as I'm not using server side templating at all right now. 

I do rather heavily :) - Not through more.chameleon just yet, but still.

**Comment by href** [comment]
I really thought this happened a few months ago :)
I finally released it! ;)

https://pypi.python.org/pypi/more.chameleon/0.2

**Comment by faassen** [comment]
Yay!
